# Generated by Django 6.0.3 on 2026-05-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну",
                max_length=100,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
