# Generated by Django 6.0.3 on 2026-03-28 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = []
	
	operations = [
		migrations.CreateModel(
			name="Category",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"name",
					models.CharField(
						max_length=150, verbose_name="Наименование категории"
					),
				),
				(
					"description",
					models.TextField(
						blank=True, null=True, verbose_name="Описание категории"
					),
				),
			],
			options={
				"verbose_name": "категория",
				"verbose_name_plural": "категории",
				"ordering": ["name"],
			},
		),
		migrations.CreateModel(
			name="Product",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"name",
					models.CharField(
						max_length=150, verbose_name="Наименование продукта"
					),
				),
				("description", models.TextField(verbose_name="Описание продукта")),
				(
					"photo",
					models.ImageField(
						blank=True,
						null=True,
						upload_to="products/photo",
						verbose_name="Изображение продукта",
					),
				),
				(
					"price",
					models.DecimalField(
						decimal_places=2, max_digits=10, verbose_name="Цена продукта"
					),
				),
				(
					"created_at",
					models.DateField(
						auto_now_add=True, verbose_name="Дата создания записи"
					),
				),
				(
					"updated_at",
					models.DateField(
						auto_now=True, verbose_name="Дата изменения записи"
					),
				),
				(
					"category",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="products",
						to="catalog.category",
						verbose_name="Категория продукта",
					),
				),
			],
			options={
				"verbose_name": "продукт",
				"verbose_name_plural": "продукты",
				"ordering": ["name"],
			},
		),
	]
