# Generated by Django 6.0.3 on 2026-03-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("catalog", "0001_initial"),
	]
	
	operations = [
		migrations.AlterField(
			model_name="product",
			name="category",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="products",
				to="catalog.category",
				verbose_name="Категория продукта",
			),
		),
	]
