# Generated by Django 6.0.3 on 2026-03-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("catalog", "0002_alter_product_category"),
	]
	
	operations = [
		migrations.AlterField(
			model_name="product",
			name="created_at",
			field=models.DateTimeField(
				auto_now_add=True, verbose_name="Дата создания записи"
			),
		),
		migrations.AlterField(
			model_name="product",
			name="photo",
			field=models.ImageField(
				blank=True,
				null=True,
				upload_to="products",
				verbose_name="Изображение продукта",
			),
		),
		migrations.AlterField(
			model_name="product",
			name="updated_at",
			field=models.DateTimeField(
				auto_now=True, verbose_name="Дата изменения записи"
			),
		),
	]
